# Mandatory
# Name of the customer
customerName: Solar System
# Mandatory
# Name of the project
name: saturn
type: product
clusterPlatform: ocp
repositories:
  - # Mandatory
    # In MS1 only envgeneInstance is supported
    type: envgeneInstance
    # Mandatory
    url: https://github.com/ormig/cloud-passport-samples.git
